Type: Socket
MonitorConfiguration: true
MonitorIntervalMilliseconds: 1000



# socket specific configuration:

Id: c1
Name: ConsumerSocketNew

SocketType: MQTT

Broker:
  HostName: "127.0.0.1"
  Port: 1883

BaseTopic: demo
PayloadType: json

DefaultSubscriptionOptions:
  Topic: docs
  QosLevel: ExactlyOnce
  ContentTypeFullName: DAT.DemoApp.Document
