Type: Socket
MonitorConfiguration: true
MonitorIntervalMilliseconds: 1000



# socket specific configuration:

Id: producer
Name: Producer

SocketType: MQTT

Broker:
  HostName: "127.0.0.1"
  Port: 1883

BaseTopic: demo
PayloadType: json

DefaultPublicationOptions:
  Topic: docs
  ResponseTopic: responses
  QosLevel: ExactlyOnce