Type: Socket
Uri: "C:/"
MonitorConfiguration: true
MonitorIntervalMilliseconds: 1000



# socket specific configuration:

Id: p1
Name: ProducerOne

SocketType: MQTT

Broker:
  Name: "127.0.0.1"
  Port: 1883

BaseTopic: demo


DefaultPublicationOptions:
  Topic: docs
  ResponseTopic: responses
  QosLevel: ExactlyOnce

DefaultSubscriptionOptions:
  Topic: docs
  QosLevel: ExactlyOnce
  ContentTypeFullName: DAT.DemoApp.Document

DefaultRequestOptions:
  Topic: docs
  ResponseTopic: responses
  GenerateResponseTopicPostfix: true